# Generated by Django 4.1.2 on 2022-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('ort', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jahr', models.CharField(max_length=4)),
            ],
        ),
    ]
