# Generated by Django 4.1.2 on 2022-10-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerto3000', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
