# Generated by Django 4.1.2 on 2022-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerto3000', '0002_rename_shows_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
